apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-mysql-conf
  namespace: petclinic
data:
  application-mysql.properties: |
    spring.datasource.url=${MYSQL_URL:jdbc:mysql://db.database.svc.cluster.local:3306/petclinic}
    spring.datasource.username=${MYSQL_USER:petclinic}
    spring.datasource.password=${MYSQL_PASS:petclinic}
    spring.sql.init.mode=always
