pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhubTocken')
    }
    stages {
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Docker build') {
            steps {
                sh "docker build --build-arg REFRESHED_AT=\$(date --rfc-3339='date') --build-arg UID=1001 --build-arg GID=1024 ./HW11-Docker-containers/"
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                docker tag 0.122.0-1 yevhenmazur/hugo
                docker push yevhenmazur/hugo
                """
            }
        }
    }
}
