#name: Docker Image CI

#on:
#  push:
#    branches: [ "main" ]

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      working-directory: HW11-Docker-containers
#      run: docker build --build-arg REFRESHED_AT=$(date --rfc-3339='date') . --tag ${{ GITHUB_ACTOR }}/hugo:$(date +%s)

name: Build & Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/hugo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./HW11-Docker-containers/
          file: ./HW11-Docker-containers/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}